name: Build
on:
  - push
  - pull_request

defaults:
  run:
    shell: bash

jobs:
  main:
    name: GHC ${{ matrix.ghc }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ghc:
          - "9.2.4"
          - "9.4.4"
          - "9.6.1"
        include:
          - os: macOS-latest
            ghc: "9.6.1"
          - os: windows-latest
            ghc: "9.6.1"
    steps:
    - uses: actions/checkout@v3
    - uses: haskell/actions/setup@v2.0.2
      id: setup-haskell-cabal
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: "latest"
        cabal-update: true
    - uses: actions/cache@v3
      name: Cache cabal stuff
      with:
        path: |
          ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}

    - name: Cabal version
      run: |
        cabal --version

    - name: Install doctest
      run: |
        mkdir -p "${{github.workspace}}/doctest-bin"
        cabal install --install-method=symlink --installdir "${{github.workspace}}/doctest-bin" doctest

    - name: Unpack
      run: |
        cabal sdist --ignore-project --output-directory .
        cabal get vector-quicksort-*.tar.gz

    - name: Build
      run: |
        cd vector-quicksort-*/
        cabal build all --enable-tests --enable-benchmarks

    - name: Test
      run: |
        cd vector-quicksort-*/
        cabal run --project-file cabal.project.test test -- --quickcheck-tests=200000 --quickcheck-max-size=1000

    - name: Doctest
      run: |
        cd vector-quicksort-*/
        cabal repl --with-ghc "${{github.workspace}}/doctest-bin/doctest" --repl-options=-Wno-missing-export-lists 'lib:vector-quicksort'

    - name: Haddock
      run: |
        cd vector-quicksort-*/
        cabal haddock all
