name: Build
on:
  - push
  - pull_request

defaults:
  run:
    shell: bash

jobs:
  main:
    name: GHC ${{ matrix.ghc }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ghc:
          - "9.2"
          - "9.4"
          - "9.6"
        include:
          - os: macOS-latest
            ghc: "9.6"
          - os: windows-latest
            ghc: "9.6"
    steps:
    - uses: actions/checkout@v3
    - uses: haskell-actions/setup@v2
      id: setup-haskell-cabal
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: "latest"
        cabal-update: true
    - uses: actions/cache@v3
      name: Cache cabal stuff
      with:
        path: |
          ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}

    - name: Cabal version
      run: |
        cabal --version

    - name: Install doctest
      run: |
        mkdir -p "${{github.workspace}}/doctest-bin"
        cabal install --install-method=symlink --installdir "${{github.workspace}}/doctest-bin" doctest

    - name: Unpack
      run: |
        cabal sdist --ignore-project --output-directory ..
        cd ..
        cabal get vector-quicksort-*.tar.gz

    - name: Build
      run: |
        cd ../vector-quicksort-*/
        cabal build all --enable-tests --enable-benchmarks

    - name: Test
      run: |
        project_file="$(pwd)/cabal.project.test"
        cd ../vector-quicksort-*/
        cabal run --project-file "$project_file" test -- --quickcheck-tests=100000 --quickcheck-max-size=1000

    - name: Doctest
      run: |
        cd ../vector-quicksort-*/
        cabal repl --with-ghc "${{github.workspace}}/doctest-bin/doctest" --repl-options=-Wno-missing-export-lists 'lib:vector-quicksort'

    - name: Haddock
      run: |
        cd ../vector-quicksort-*/
        cabal haddock all

    - name: Cabal check
      run: |
        cd ../vector-quicksort-*/
        cabal check

  i386:
    runs-on: ubuntu-latest
    container:
      image: i386/ubuntu:bionic

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ghc:
          - "9.2"
          - "9.4"
          - "9.6"

    steps:
    - name: Install
      run: |
        apt-get update -y
        apt-get install -y autoconf build-essential zlib1g-dev libgmp-dev curl libncurses5 libtinfo5 libncurses5-dev libtinfo-dev

        curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | BOOTSTRAP_HASKELL_NONINTERACTIVE=1 BOOTSTRAP_HASKELL_MINIMAL=1 sh

        source ~/.ghcup/env
        ghcup install ghc --set ${{ matrix.ghc }}
        ghcup install cabal latest

    - uses: actions/checkout@v1

    - name: Cabal version
      run: |
        source ~/.ghcup/env
        cabal --version

    - name: Unpack
      run: |
        source ~/.ghcup/env

        cabal sdist --ignore-project --output-directory ..
        cd ..
        cabal get vector-quicksort-*.tar.gz

    - name: Build
      run: |
        source ~/.ghcup/env
        cabal update

        project_file="$(pwd)/cabal.project.test"
        cd ../vector-quicksort-*/
        cabal build --project-file "$project_file" --enable-tests --enable-benchmarks all

    - name: Test
      run: |
        export LANG="C.UTF-8"
        source ~/.ghcup/env

        project_file="$(pwd)/cabal.project.test"
        cd ../vector-quicksort-*/

        cabal run --project-file "$project_file" test -- --quickcheck-tests=10000 --quickcheck-max-size=256

        cabal bench --project-file "$project_file" --benchmark-options='--stdev 100 --timeout 600' all


